# Generated by Django 6.0.2 on 2026-02-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstracker',
            name='total_correct_answers',
            field=models.IntegerField(default=0, help_text='Total number of questions answered correctly'),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='total_mock_exams_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='total_questions_attempted',
            field=models.IntegerField(default=0, help_text='Total number of questions answered across all quizzes'),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='tutor_interactions_count',
            field=models.IntegerField(default=0, help_text='Total number of messages sent to AI tutor'),
        ),
    ]
