# Generated by Django 6.0.2 on 2026-02-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_progresstracker_total_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
