# Generated by Django 6.0.2 on 2026-02-14 15:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('plan_type', models.CharField(choices=[('ai_generated', 'AI Generated'), ('custom', 'Custom'), ('template', 'Template-based')], default='ai_generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_date', models.DateField(help_text='Target exam date')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='draft', max_length=20)),
                ('total_topics', models.IntegerField(default=0)),
                ('completed_topics', models.IntegerField(default=0)),
                ('total_estimated_study_hours', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_study_hours', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('study_hours_per_day', models.FloatField(default=2.5, help_text='Target hours for daily study', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(12)])),
                ('study_days_per_week', models.IntegerField(default=6, help_text='Days available for study per week', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('difficulty_preference', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('include_weekends', models.BooleanField(default=True)),
                ('ai_prompt_used', models.TextField(blank=True, help_text='The prompt used to generate this plan')),
                ('ai_provider', models.CharField(blank=True, help_text='Which AI service generated this plan', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in the generated plan', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('average_daily_progress', models.FloatField(default=0.0, help_text='Percentage of plan completed')),
                ('exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.examtype')),
                ('subjects', models.ManyToManyField(related_name='study_plans', to='content.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start_date', models.DateField()),
                ('scheduled_end_date', models.DateField()),
                ('scheduled_start_time', models.TimeField(blank=True, null=True)),
                ('scheduled_end_time', models.TimeField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('actual_time_spent_seconds', models.IntegerField(default=0)),
                ('estimated_duration_hours', models.FloatField(default=1.0, help_text='Estimated hours to complete this task', validators=[django.core.validators.MinValueValidator(0.25)])),
                ('description', models.TextField(blank=True)),
                ('learning_objectives', models.JSONField(default=list, help_text='List of learning objectives for this task')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('revisit', 'Revisit Required')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('completion_percentage', models.FloatField(default=0.0, help_text='Percentage of task completed', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('understanding_level', models.IntegerField(default=0, help_text="User's understanding of the topic (0-100)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_repeatable', models.BooleanField(default=False, help_text='Task can be repeated for reinforcement')),
                ('repeat_count', models.IntegerField(default=0)),
                ('max_repeats', models.IntegerField(default=3)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resource_links', models.JSONField(default=list, help_text='Links to study materials')),
                ('question_ids', models.JSONField(default=list, help_text='IDs of questions related to this task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='study_plans.studyplan')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.topic')),
            ],
            options={
                'ordering': ['scheduled_start_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='StudyReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('task_start', 'Task Start Reminder'), ('task_deadline', 'Task Deadline Reminder'), ('weak_topic', 'Weak Topic Review'), ('daily_goal', 'Daily Goal Reminder')], max_length=20)),
                ('frequency', models.CharField(choices=[('once', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='once', max_length=20)),
                ('scheduled_datetime', models.DateTimeField()),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('next_send', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='study_plans.studyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_reminders', to=settings.AUTH_USER_MODEL)),
                ('study_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='study_plans.studytask')),
            ],
            options={
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('difficulty_increase', 'Difficulty Increased'), ('difficulty_decrease', 'Difficulty Decreased'), ('pace_adjustment', 'Study Pace Adjusted'), ('topic_added', 'Topic Added'), ('topic_removed', 'Topic Removed'), ('deadline_extended', 'Deadline Extended'), ('priority_updated', 'Priority Updated')], max_length=30)),
                ('reason', models.TextField()),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('performance_metric', models.CharField(blank=True, help_text="Metric that triggered adjustment (e.g., 'accuracy_score')", max_length=50)),
                ('performance_threshold', models.FloatField(blank=True, null=True)),
                ('actual_performance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='study_plans.studyplan')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_plans.studytask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user', '-created_at'], name='study_plans_user_id_0b4e01_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['user', 'status'], name='study_plans_user_id_5fa245_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['exam_date'], name='study_plans_exam_da_add473_idx'),
        ),
        migrations.AddIndex(
            model_name='studytask',
            index=models.Index(fields=['study_plan', 'scheduled_start_date'], name='study_plans_study_p_048dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='studytask',
            index=models.Index(fields=['study_plan', 'status'], name='study_plans_study_p_87aa72_idx'),
        ),
        migrations.AddIndex(
            model_name='studytask',
            index=models.Index(fields=['topic', 'scheduled_start_date'], name='study_plans_topic_i_483015_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studytask',
            unique_together={('study_plan', 'topic', 'scheduled_start_date')},
        ),
        migrations.AddIndex(
            model_name='studyreminder',
            index=models.Index(fields=['user', 'is_active'], name='study_plans_user_id_4578b8_idx'),
        ),
        migrations.AddIndex(
            model_name='studyreminder',
            index=models.Index(fields=['scheduled_datetime'], name='study_plans_schedul_9ae2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='adjustmenthistory',
            index=models.Index(fields=['study_plan', 'adjustment_type'], name='study_plans_study_p_feb7ff_idx'),
        ),
    ]
