# Generated by Django 6.0.2 on 2026-02-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0001_initial'),
        ('questions', '0001_initial'),
        ('study_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytask',
            name='chat_session',
            field=models.ForeignKey(blank=True, help_text='AI Tutor session for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_tasks', to='ai_tutor.chatsession'),
        ),
        migrations.AddField(
            model_name='studytask',
            name='questions',
            field=models.ManyToManyField(blank=True, help_text='Questions linked to this task', related_name='study_tasks', to='questions.question'),
        ),
    ]
