# Generated by Django 6.0.2 on 2026-02-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plans', '0002_studytask_chat_session_studytask_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
