# Generated by Django 6.0.2 on 2026-02-15 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('study_plans', '0003_studyplan_is_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlanAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('exit_quiz', 'Plan Exit Quiz'), ('mock_exam', 'Full Mock Exam')], max_length=20)),
                ('passing_score', models.FloatField(default=70.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_assessments', to='quiz.quizattempt')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assessments', to='quiz.quiz')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='study_plans.studyplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('study_plan', 'assessment_type', 'quiz')},
            },
        ),
    ]
