# Generated by Django 6.0.2 on 2026-02-14 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('launch_date', models.DateField(null=True)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('STEM', 'Science, Technology, Engineering, Math'), ('HUMANITIES', 'Humanities & Social Sciences'), ('LANGUAGES', 'Languages'), ('ARTS', 'Creative Arts'), ('COMMERCE', 'Business & Commerce'), ('VOCATIONAL', 'Vocational & Technical')], max_length=20)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('color', models.CharField(default='#FF6B35', max_length=7)),
                ('description', models.TextField()),
                ('is_core', models.BooleanField(default=False)),
                ('aliases', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('is_international', models.BooleanField(default=False)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='exam_boards/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.country')),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('PRIMARY', 'Primary School'), ('JUNIOR', 'Junior Secondary'), ('SENIOR', 'Senior Secondary'), ('TERTIARY', 'Tertiary Entry'), ('PROFESSIONAL', 'Professional Certification')], max_length=20)),
                ('duration_minutes', models.IntegerField()),
                ('passing_score', models.IntegerField(null=True)),
                ('max_score', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('exam_format', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.examboard')),
            ],
            options={
                'unique_together': {('name', 'exam_board')},
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('version', models.CharField(max_length=50)),
                ('document_url', models.URLField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.examtype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.subject')),
            ],
            options={
                'verbose_name_plural': 'Syllabi',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('estimated_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('description', models.TextField()),
                ('learning_objectives', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='content.topic')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.subject')),
            ],
            options={
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(null=True)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.syllabus')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.topic')),
            ],
        ),
        migrations.AddField(
            model_name='syllabus',
            name='topics',
            field=models.ManyToManyField(through='content.SyllabusTopic', to='content.topic'),
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('content_summary', models.TextField()),
                ('key_concepts', models.JSONField(default=list)),
                ('formulas', models.JSONField(default=list)),
                ('examples', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='content.topic')),
            ],
            options={
                'ordering': ['topic', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TopicExamMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('typical_questions', models.IntegerField()),
                ('last_appeared', models.IntegerField(null=True)),
                ('frequency', models.CharField(max_length=20)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.examtype')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.topic')),
            ],
            options={
                'unique_together': {('topic', 'exam_type')},
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='exam_types',
            field=models.ManyToManyField(through='content.TopicExamMapping', to='content.examtype'),
        ),
        migrations.CreateModel(
            name='ExamTypeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=False)),
                ('max_questions', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('syllabus_url', models.URLField(blank=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.examtype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.subject')),
            ],
            options={
                'unique_together': {('exam_type', 'subject')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('exam_type', 'subject', 'year')},
        ),
    ]
