# Generated by Django 6.0.2 on 2026-02-14 15:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionFeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_used_today', models.PositiveIntegerField(default=0)),
                ('last_questions_reset', models.DateField(auto_now_add=True)),
                ('study_sessions_this_month', models.PositiveIntegerField(default=0)),
                ('last_sessions_reset', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_feature_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Feature Usage',
                'verbose_name_plural': 'Subscription Feature Usages',
                'db_table': 'subscriptions_feature_usage',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='User-friendly plan name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price in ₦', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('duration_days', models.PositiveIntegerField(default=0, help_text='Duration in days (0 for free/unlimited)')),
                ('questions_per_day', models.PositiveIntegerField(default=10, help_text='Number of questions user can access per day')),
                ('has_mock_exams', models.BooleanField(default=False, help_text='Access to mock exams')),
                ('has_ai_tutor', models.BooleanField(default=False, help_text='Access to AI tutor')),
                ('has_audio_mode', models.BooleanField(default=False, help_text='Access to audio learning mode')),
                ('has_document_mode', models.BooleanField(default=False, help_text='Access to document analysis mode')),
                ('has_offline_mode', models.BooleanField(default=False, help_text='Access to offline learning')),
                ('has_premium_content', models.BooleanField(default=False, help_text='Access to premium learning materials')),
                ('has_priority_support', models.BooleanField(default=False, help_text='Priority customer support')),
                ('study_sessions_per_month', models.PositiveIntegerField(default=0, help_text='0 means unlimited')),
                ('max_topics', models.PositiveIntegerField(default=0, help_text='Maximum topics user can study (0 for unlimited)')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions_plan',
                'ordering': ['duration_days', 'price'],
                'indexes': [models.Index(fields=['name'], name='subscriptio_name_ec7d9f_idx'), models.Index(fields=['is_active'], name='subscriptio_is_acti_8f27d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='inactive', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When subscription expires', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('paystack_authorization_code', models.CharField(blank=True, help_text='Authorization code from Paystack for recurring charges', max_length=255, null=True)),
                ('paystack_customer_code', models.CharField(blank=True, help_text='Customer code from Paystack', max_length=255, null=True)),
                ('paystack_subscription_code', models.CharField(blank=True, help_text='Paystack subscription code for recurring billing', max_length=255, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'db_table': 'subscriptions_user_subscription',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('paystack', 'Paystack'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('manual', 'Manual')], default='paystack', max_length=20)),
                ('paystack_reference', models.CharField(blank=True, help_text='Paystack transaction reference', max_length=255, null=True, unique=True)),
                ('paystack_access_code', models.CharField(blank=True, max_length=255, null=True)),
                ('paystack_authorization_code', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='subscriptions.subscriptionplan')),
                ('user_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='subscriptions.usersubscription')),
            ],
            options={
                'db_table': 'subscriptions_payment_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Invoice reference number', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='subscriptions.paymenttransaction')),
            ],
            options={
                'db_table': 'subscriptions_invoice',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['user'], name='subscriptio_user_id_768d7d_idx'), models.Index(fields=['status'], name='subscriptio_status_10461a_idx'), models.Index(fields=['invoice_number'], name='subscriptio_invoice_50e7d3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user'], name='subscriptio_user_id_08abe6_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status'], name='subscriptio_status_6bf742_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['plan'], name='subscriptio_plan_id_fb1658_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['expires_at'], name='subscriptio_expires_45b4c8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_19a6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['paystack_reference'], name='subscriptio_paystac_cce992_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='subscriptio_status_eddc82_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='subscriptio_created_07b1a8_idx'),
        ),
    ]
