# Generated by Django 6.0.2 on 2026-02-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('THEORY', 'Theory/Essay'), ('TRUE_FALSE', 'True/False'), ('FILL_BLANK', 'Fill in the Blanks'), ('MATCHING', 'Matching'), ('ORDERING', 'Ordering')], db_index=True, default='MCQ', max_length=20),
        ),
    ]
