# Generated by Django 6.0.2 on 2026-02-14 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('is_submitted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('TIME_UP', 'Time Up')], default='IN_PROGRESS', max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('percentage', models.FloatField(default=0.0)),
                ('raw_responses', models.JSONField(blank=True, default=dict, help_text='User answers by question id')),
                ('auto_graded', models.BooleanField(default=False)),
                ('attempted_questions', models.PositiveIntegerField(default=0, help_text='Count of answered questions')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField()),
                ('percentage', models.FloatField()),
                ('passed', models.BooleanField(default=False)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('incorrect_answers', models.PositiveIntegerField(default=0)),
                ('unanswered', models.PositiveIntegerField(default=0)),
                ('detailed_breakdown', models.JSONField(blank=True, default=dict, help_text='Per-question and per-topic analysis')),
                ('performance_summary', models.JSONField(blank=True, default=dict, help_text='Summary of performance by topic')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='AI-generated recommendations')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='exams.examattempt')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Exam description and instructions')),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('passing_score', models.PositiveIntegerField(default=40, help_text='Percentage required to pass')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.examtype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='examattempt',
            name='mock_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinattempt_set', to='exams.mockexam'),
        ),
        migrations.CreateModel(
            name='MockExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('mock_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.mockexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='mockexam',
            name='questions',
            field=models.ManyToManyField(through='exams.MockExamQuestion', to='questions.question'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'mock_exam'], name='exams_exama_user_id_4f9054_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'started_at'], name='exams_exama_user_id_27ebe8_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status'], name='exams_exama_status_6897fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mockexamquestion',
            unique_together={('mock_exam', 'question')},
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['exam_type', 'subject'], name='exams_mocke_exam_ty_1f58ff_idx'),
        ),
        migrations.AddIndex(
            model_name='mockexam',
            index=models.Index(fields=['is_active', 'is_public'], name='exams_mocke_is_acti_12f30e_idx'),
        ),
    ]
