# Generated by Django 6.0.2 on 2026-02-14 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Unique code for students to join', max_length=10, unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(help_text='The user who manages this institution', on_delete=django.db.models.deletion.CASCADE, related_name='managed_institution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='institutions.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('institution', 'student')},
            },
        ),
    ]
