# Generated by Django 6.0.2 on 2026-02-17 23:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_examtype_options_alter_subject_options'),
        ('study_tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(help_text='The question or prompt')),
                ('back', models.TextField(help_text='The answer or explanation')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=0, help_text='Interval in days')),
                ('repetitions', models.IntegerField(default=0)),
                ('next_review', models.DateField(default=django.utils.timezone.now)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('ai_generated', 'AI Generated'), ('exam_mistake', 'Exam Mistake')], default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='0: Again, 1: Hard, 2: Good, 3: Easy')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('old_interval', models.IntegerField()),
                ('old_ease_factor', models.FloatField()),
                ('new_interval', models.IntegerField()),
                ('new_ease_factor', models.FloatField()),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='study_tools.flashcard')),
            ],
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'next_review'], name='study_tools_user_id_fefc9f_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['subject', 'topic'], name='study_tools_subject_f8ab7a_idx'),
        ),
    ]
